In [1]:
import sys

sys.path.append('../../')
from ml_factory.datasets.precompute_tokens import precompute_tokens
from ml_factory.utils import merge_parts_to_dir
from ml_factory import DATA_RAW_DIR, DATA_PROCESSED_DIR
from transformers import AutoTokenizer
import torch
from pathlib import Path
from ml_factory.datasets import PromptBERTDataset
from torch.utils.data import Subset, DataLoader
from ml_factory.datasets.sampler import SplitSampler
import numpy as np
import torch

from torch.utils.data import Subset, DataLoader
from transformers import AutoModelForSequenceClassification
from tqdm.auto import tqdm

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score
)
import numpy as np
from torch.utils.data import Subset, DataLoader

In [ ]:
data_path = DATA_RAW_DIR / 'final_data_cleaner.parquet'
output_path = DATA_PROCESSED_DIR / '32_128_processed_mini'

In [ ]:

dataset = PromptBERTDataset(output_path)
sampler_data = torch.load(
    DATA_PROCESSED_DIR / "splitsampler_train_7_test_15.pt",
    weights_only=False
)

print(type(sampler_data["split"]))
print(sampler_data["split"].keys())
import torch
from torch.utils.data import Subset, DataLoader

# Load previously saved split
sampler_data = torch.load(
    DATA_PROCESSED_DIR / "splitsampler_train_7_test_15.pt",
    weights_only=False
)

# Get the actual IDs
train_ids = sampler_data["split"]["train"]
val_ids = sampler_data["split"]["validation"]
test_ids = sampler_data["split"]["test"]

# Create datasets using the saved IDs
train_dataset = Subset(
    dataset,
    dataset.ids_to_position(train_ids)
)

val_dataset = Subset(
    dataset,
    dataset.ids_to_position(val_ids)
)

test_dataset = Subset(
    dataset,
    dataset.ids_to_position(test_ids)
)
# train_loader = DataLoader(train_dataset, shuffle=True, batch_size=100)
val_loader = DataLoader(val_dataset, shuffle=False, batch_size=100)
test_loader = DataLoader(test_dataset, shuffle=False, batch_size=100)

n = 5
batch_size = 100
seed = 42

# Original 70% training prompt IDs
train_ids = np.array(sampler_data["split"]["train"])

# Shuffle and divide prompts among 5 BERTs
rng = np.random.default_rng(seed)
rng.shuffle(train_ids)

train_id_subsets = np.array_split(train_ids, n)

# Convert prompt IDs -> all corresponding chunk positions
train_subsets = [
    Subset(dataset, dataset.ids_to_position(ids.tolist()))
    for ids in train_id_subsets
]

# DataLoaders
ensemble_train_loaders = [
    DataLoader(subset, batch_size=batch_size, shuffle=True)
    for subset in train_subsets
]
for i, subset in enumerate(train_subsets):
    print(f"BERT {i+1}: {len(train_id_subsets[i])} prompts -> {len(subset)} chunks")

<class 'dict'>
dict_keys(['train', 'validation', 'test'])
BERT 1: 50723 prompts -> 58473 chunks
BERT 2: 50722 prompts -> 58484 chunks
BERT 3: 50722 prompts -> 58454 chunks
BERT 4: 50722 prompts -> 58707 chunks
BERT 5: 50722 prompts -> 58477 chunks

In [3]:
test_loader

In [4]:
MODEL_NAME = "google/bert_uncased_L-4_H-256_A-4"

In [7]:
# ============================================================
# CONFIG
# ============================================================

num_models = 5
num_epochs = 5

learning_rate = 2e-5
weight_decay = 0.01

warmup_ratio = 0.10
max_grad_norm = 1.0


patience = 2

base_seed = 42

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

Device: cuda

In [8]:
from transformers import get_linear_schedule_with_warmup

In [9]:
# ============================================================
# STORAGE
# ============================================================

ensemble_models = []
validation_results = []


# ============================================================
# TRAIN ENSEMBLE
# ============================================================

for model_idx, train_loader in enumerate(ensemble_train_loaders):

    print("\n" + "=" * 70)
    print(f"TRAINING BERT {model_idx + 1}/{num_models}")
    print("=" * 70)


    # ========================================================
    # REPRODUCIBILITY
    # ========================================================

    model_seed = base_seed + model_idx

    torch.manual_seed(model_seed)
    np.random.seed(model_seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(model_seed)


    # ========================================================
    # CREATE FRESH BERT-MINI
    # ========================================================

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    ).to(device)


    # ========================================================
    # OPTIMIZER
    # ========================================================

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=learning_rate,
        weight_decay=weight_decay
    )


    # ========================================================
    # SCHEDULER
    # ========================================================

    num_training_steps = (
        len(train_loader) * num_epochs
    )

    num_warmup_steps = int(
        warmup_ratio * num_training_steps
    )

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps
    )


    print(
        f"Training steps: {num_training_steps}"
    )

    print(
        f"Warmup steps: {num_warmup_steps}"
    )


    # ========================================================
    # BEST CHECKPOINT
    # ========================================================

    best_val_f1 = -float("inf")
    best_model_state = None
    best_epoch = None

    epochs_without_improvement = 0


    # ========================================================
    # EPOCH LOOP
    # ========================================================

    for epoch in range(num_epochs):

        # ====================================================
        # TRAINING
        # ====================================================

        model.train()

        train_loss = 0.0

        progress_bar = tqdm(
            train_loader,
            desc=(
                f"BERT {model_idx + 1} | "
                f"Epoch {epoch + 1}/{num_epochs}"
            )
        )


        for batch in progress_bar:

            input_ids = batch["tokenized"].to(device)
            attention_mask = batch["attention_masks"].to(device)
            labels = batch["label"].to(device)


            # ------------------------------------------------
            # CLEAR GRADIENTS
            # ------------------------------------------------

            optimizer.zero_grad()


            # ------------------------------------------------
            # FORWARD PASS
            # ------------------------------------------------

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            loss = outputs.loss


            # ------------------------------------------------
            # BACKWARD PASS
            # ------------------------------------------------

            loss.backward()


            # ------------------------------------------------
            # GRADIENT CLIPPING
            # ------------------------------------------------

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_grad_norm
            )


            # ------------------------------------------------
            # OPTIMIZER
            # ------------------------------------------------

            optimizer.step()


            # ------------------------------------------------
            # LEARNING-RATE SCHEDULER
            # ------------------------------------------------

            scheduler.step()


            # ------------------------------------------------
            # TRACK LOSS
            # ------------------------------------------------

            train_loss += loss.item()


            # ------------------------------------------------
            # PROGRESS BAR
            # ------------------------------------------------

            current_lr = scheduler.get_last_lr()[0]

            progress_bar.set_postfix(
                loss=f"{loss.item():.4f}",
                lr=f"{current_lr:.2e}"
            )


        # ====================================================
        # AVERAGE TRAINING LOSS
        # ====================================================

        avg_train_loss = (
            train_loss / len(train_loader)
        )


        # ====================================================
        # VALIDATION
        # ====================================================

        model.eval()

        val_loss = 0.0

        all_labels = []
        all_predictions = []
        all_probabilities = []


        with torch.no_grad():

            for batch in val_loader:

                input_ids = batch["tokenized"].to(device)
                attention_mask = batch["attention_masks"].to(device)
                labels = batch["label"].to(device)


                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    labels=labels
                )


                val_loss += outputs.loss.item()


                logits = outputs.logits


                probabilities = torch.softmax(
                    logits,
                    dim=1
                )[:, 1]


                predictions = torch.argmax(
                    logits,
                    dim=1
                )


                all_labels.extend(
                    labels.cpu().numpy()
                )

                all_predictions.extend(
                    predictions.cpu().numpy()
                )

                all_probabilities.extend(
                    probabilities.cpu().numpy()
                )


        # ====================================================
        # VALIDATION METRICS
        # ====================================================

        avg_val_loss = (
            val_loss / len(val_loader)
        )

        val_accuracy = accuracy_score(
            all_labels,
            all_predictions
        )

        val_precision = precision_score(
            all_labels,
            all_predictions,
            zero_division=0
        )

        val_recall = recall_score(
            all_labels,
            all_predictions,
            zero_division=0
        )

        val_f1 = f1_score(
            all_labels,
            all_predictions,
            zero_division=0
        )

        val_roc_auc = roc_auc_score(
            all_labels,
            all_probabilities
        )

        val_pr_auc = average_precision_score(
            all_labels,
            all_probabilities
        )


        # ====================================================
        # CURRENT LEARNING RATE
        # ====================================================

        current_lr = scheduler.get_last_lr()[0]


        # ====================================================
        # PRINT RESULTS
        # ====================================================

        print(
            f"Epoch {epoch + 1}/{num_epochs} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Loss: {avg_val_loss:.4f} | "
            f"F1: {val_f1:.4f} | "
            f"PR-AUC: {val_pr_auc:.4f} | "
            f"ROC-AUC: {val_roc_auc:.4f} | "
            f"LR: {current_lr:.2e}"
        )


        # ====================================================
        # SAVE BEST MODEL
        # ====================================================

        if val_f1 > best_val_f1:

            best_val_f1 = val_f1
            best_epoch = epoch + 1

            best_model_state = {
                k: v.cpu().clone()
                for k, v in model.state_dict().items()
            }

            epochs_without_improvement = 0

        else:

            epochs_without_improvement += 1


        # ====================================================
        # EARLY STOPPING
        # ====================================================

        if epochs_without_improvement >= patience:

            print(
                f"Early stopping after "
                f"{epoch + 1} epochs."
            )

            break


    # ========================================================
    # RESTORE BEST CHECKPOINT
    # ========================================================

    model.load_state_dict(best_model_state)

    model.to(device)


    # ========================================================
    # STORE MODEL
    # ========================================================

    ensemble_models.append(model)


    validation_results.append({
        "model": model_idx + 1,
        "best_epoch": best_epoch,
        "best_val_f1": best_val_f1
    })


    # ========================================================
    # REPORT
    # ========================================================

    print(
        f"\nBERT {model_idx + 1} "
        f"best epoch: {best_epoch}"
    )

    print(
        f"BERT {model_idx + 1} "
        f"best validation F1: {best_val_f1:.4f}"
    )


# ============================================================
# COMPLETE
# ============================================================

print("\n" + "=" * 70)
print("ALL 5 BERT-MINI MODELS HAVE BEEN TRAINED")
print("=" * 70)


for result in validation_results:

    print(
        f"BERT {result['model']}: "
        f"Best Epoch = {result['best_epoch']} | "
        f"Best Val F1 = {result['best_val_f1']:.4f}"
    )

======================================================================
TRAINING BERT 1/5
======================================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training steps: 2925
Warmup steps: 292

BERT 1 | Epoch 1/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 1/5 | Train Loss: 0.3729 | Val Loss: 0.1530 | F1: 0.9480 | PR-AUC: 0.9908 | ROC-AUC: 0.9886 | LR: 1.78e-05

BERT 1 | Epoch 2/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 2/5 | Train Loss: 0.1408 | Val Loss: 0.1130 | F1: 0.9596 | PR-AUC: 0.9944 | ROC-AUC: 0.9931 | LR: 1.33e-05

BERT 1 | Epoch 3/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 3/5 | Train Loss: 0.1064 | Val Loss: 0.0995 | F1: 0.9652 | PR-AUC: 0.9955 | ROC-AUC: 0.9944 | LR: 8.89e-06

BERT 1 | Epoch 4/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 4/5 | Train Loss: 0.0874 | Val Loss: 0.0963 | F1: 0.9671 | PR-AUC: 0.9960 | ROC-AUC: 0.9950 | LR: 4.44e-06

BERT 1 | Epoch 5/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 5/5 | Train Loss: 0.0808 | Val Loss: 0.0966 | F1: 0.9671 | PR-AUC: 0.9961 | ROC-AUC: 0.9951 | LR: 0.00e+00

BERT 1 best epoch: 5
BERT 1 best validation F1: 0.9671

======================================================================
TRAINING BERT 2/5
======================================================================

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training steps: 2925
Warmup steps: 292

BERT 2 | Epoch 1/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 1/5 | Train Loss: 0.3598 | Val Loss: 0.1508 | F1: 0.9468 | PR-AUC: 0.9902 | ROC-AUC: 0.9878 | LR: 1.78e-05

BERT 2 | Epoch 2/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 2/5 | Train Loss: 0.1372 | Val Loss: 0.1098 | F1: 0.9610 | PR-AUC: 0.9944 | ROC-AUC: 0.9930 | LR: 1.33e-05

BERT 2 | Epoch 3/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 3/5 | Train Loss: 0.1035 | Val Loss: 0.0986 | F1: 0.9649 | PR-AUC: 0.9954 | ROC-AUC: 0.9944 | LR: 8.89e-06

BERT 2 | Epoch 4/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 4/5 | Train Loss: 0.0885 | Val Loss: 0.0962 | F1: 0.9665 | PR-AUC: 0.9958 | ROC-AUC: 0.9949 | LR: 4.44e-06

BERT 2 | Epoch 5/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 5/5 | Train Loss: 0.0795 | Val Loss: 0.0963 | F1: 0.9671 | PR-AUC: 0.9959 | ROC-AUC: 0.9950 | LR: 0.00e+00

BERT 2 best epoch: 5
BERT 2 best validation F1: 0.9671

======================================================================
TRAINING BERT 3/5
======================================================================

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training steps: 2925
Warmup steps: 292

BERT 3 | Epoch 1/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 1/5 | Train Loss: 0.3707 | Val Loss: 0.1426 | F1: 0.9505 | PR-AUC: 0.9912 | ROC-AUC: 0.9890 | LR: 1.78e-05

BERT 3 | Epoch 2/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 2/5 | Train Loss: 0.1372 | Val Loss: 0.1133 | F1: 0.9603 | PR-AUC: 0.9943 | ROC-AUC: 0.9930 | LR: 1.33e-05

BERT 3 | Epoch 3/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 3/5 | Train Loss: 0.1046 | Val Loss: 0.0988 | F1: 0.9652 | PR-AUC: 0.9956 | ROC-AUC: 0.9945 | LR: 8.89e-06

BERT 3 | Epoch 4/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 4/5 | Train Loss: 0.0874 | Val Loss: 0.0965 | F1: 0.9664 | PR-AUC: 0.9959 | ROC-AUC: 0.9949 | LR: 4.44e-06

BERT 3 | Epoch 5/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 5/5 | Train Loss: 0.0783 | Val Loss: 0.0962 | F1: 0.9669 | PR-AUC: 0.9960 | ROC-AUC: 0.9951 | LR: 0.00e+00

BERT 3 best epoch: 5
BERT 3 best validation F1: 0.9669

======================================================================
TRAINING BERT 4/5
======================================================================

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training steps: 2940
Warmup steps: 294

BERT 4 | Epoch 1/5:   0%|          | 0/588 [00:00<?, ?it/s]

Epoch 1/5 | Train Loss: 0.3544 | Val Loss: 0.1489 | F1: 0.9492 | PR-AUC: 0.9908 | ROC-AUC: 0.9886 | LR: 1.78e-05

BERT 4 | Epoch 2/5:   0%|          | 0/588 [00:00<?, ?it/s]

Epoch 2/5 | Train Loss: 0.1365 | Val Loss: 0.1143 | F1: 0.9599 | PR-AUC: 0.9944 | ROC-AUC: 0.9931 | LR: 1.33e-05

BERT 4 | Epoch 3/5:   0%|          | 0/588 [00:00<?, ?it/s]

Epoch 3/5 | Train Loss: 0.1045 | Val Loss: 0.0980 | F1: 0.9656 | PR-AUC: 0.9957 | ROC-AUC: 0.9946 | LR: 8.89e-06

BERT 4 | Epoch 4/5:   0%|          | 0/588 [00:00<?, ?it/s]

Epoch 4/5 | Train Loss: 0.0852 | Val Loss: 0.0961 | F1: 0.9673 | PR-AUC: 0.9959 | ROC-AUC: 0.9950 | LR: 4.44e-06

BERT 4 | Epoch 5/5:   0%|          | 0/588 [00:00<?, ?it/s]

Epoch 5/5 | Train Loss: 0.0763 | Val Loss: 0.0980 | F1: 0.9671 | PR-AUC: 0.9960 | ROC-AUC: 0.9951 | LR: 0.00e+00

BERT 4 best epoch: 4
BERT 4 best validation F1: 0.9673

======================================================================
TRAINING BERT 5/5
======================================================================

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Training steps: 2925
Warmup steps: 292

BERT 5 | Epoch 1/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 1/5 | Train Loss: 0.3618 | Val Loss: 0.1493 | F1: 0.9476 | PR-AUC: 0.9907 | ROC-AUC: 0.9883 | LR: 1.78e-05

BERT 5 | Epoch 2/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 2/5 | Train Loss: 0.1391 | Val Loss: 0.1096 | F1: 0.9610 | PR-AUC: 0.9945 | ROC-AUC: 0.9932 | LR: 1.33e-05

BERT 5 | Epoch 3/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 3/5 | Train Loss: 0.1035 | Val Loss: 0.1002 | F1: 0.9647 | PR-AUC: 0.9956 | ROC-AUC: 0.9945 | LR: 8.89e-06

BERT 5 | Epoch 4/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 4/5 | Train Loss: 0.0864 | Val Loss: 0.0977 | F1: 0.9660 | PR-AUC: 0.9959 | ROC-AUC: 0.9949 | LR: 4.44e-06

BERT 5 | Epoch 5/5:   0%|          | 0/585 [00:00<?, ?it/s]

Epoch 5/5 | Train Loss: 0.0776 | Val Loss: 0.0949 | F1: 0.9670 | PR-AUC: 0.9961 | ROC-AUC: 0.9951 | LR: 0.00e+00

BERT 5 best epoch: 5
BERT 5 best validation F1: 0.9670

======================================================================
ALL 5 BERT-MINI MODELS HAVE BEEN TRAINED
======================================================================
BERT 1: Best Epoch = 5 | Best Val F1 = 0.9671
BERT 2: Best Epoch = 5 | Best Val F1 = 0.9671
BERT 3: Best Epoch = 5 | Best Val F1 = 0.9669
BERT 4: Best Epoch = 4 | Best Val F1 = 0.9673
BERT 5: Best Epoch = 5 | Best Val F1 = 0.9670

In [17]:
len(ensemble_models)

5

In [15]:
MODEL_SAVE_DIR = (
    DATA_PROCESSED_DIR / "ensemble_classifier_mini"
)

MODEL_SAVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

for i, model in enumerate(ensemble_models):

    model_save_path = (
        MODEL_SAVE_DIR / f"bert_{i + 1}.pt"
    )

    torch.save(
        model.state_dict(),
        model_save_path
    )

    print(
        f"BERT {i + 1} saved to: {model_save_path}"
    )

BERT 1 saved to: c:\Users\Jivesh Gawde\Documents\NMIMS\sem3\FortexAI\Backend\ml_factory\notebooks\..\..\ml_factory\data\processed\ensemble_classifier_mini\bert_1.pt
BERT 2 saved to: c:\Users\Jivesh Gawde\Documents\NMIMS\sem3\FortexAI\Backend\ml_factory\notebooks\..\..\ml_factory\data\processed\ensemble_classifier_mini\bert_2.pt
BERT 3 saved to: c:\Users\Jivesh Gawde\Documents\NMIMS\sem3\FortexAI\Backend\ml_factory\notebooks\..\..\ml_factory\data\processed\ensemble_classifier_mini\bert_3.pt
BERT 4 saved to: c:\Users\Jivesh Gawde\Documents\NMIMS\sem3\FortexAI\Backend\ml_factory\notebooks\..\..\ml_factory\data\processed\ensemble_classifier_mini\bert_4.pt
BERT 5 saved to: c:\Users\Jivesh Gawde\Documents\NMIMS\sem3\FortexAI\Backend\ml_factory\notebooks\..\..\ml_factory\data\processed\ensemble_classifier_mini\bert_5.pt

In [5]:
MODEL_NAME = "google/bert_uncased_L-4_H-256_A-4"

MODEL_SAVE_DIR = DATA_PROCESSED_DIR / "ensemble_classifier_mini"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

loaded_models = []

for i in range(1, 6):
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )

    state_dict = torch.load(
        MODEL_SAVE_DIR / f"bert_{i}.pt",
        map_location=device
    )

    model.load_state_dict(state_dict)
    model.to(device)
    model.eval()

    loaded_models.append(model)

print(f"Loaded {len(loaded_models)} models.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/71 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-4_H-256_A-4
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loaded 5 models.

In [21]:
import pandas as pd

In [22]:
validation_results = []

for model_idx, model in enumerate(loaded_models):

    model.eval()

    val_loss = 0.0
    all_labels = []
    all_predictions = []
    all_probabilities = []

    with torch.no_grad():

        for batch in val_loader:

            input_ids = batch["tokenized"].to(device)
            attention_mask = batch["attention_masks"].to(device)
            labels = batch["label"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            val_loss += outputs.loss.item()

            logits = outputs.logits
            probabilities = torch.softmax(logits, dim=1)[:, 1]
            predictions = torch.argmax(logits, dim=1)

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())
            all_probabilities.extend(probabilities.cpu().numpy())

    avg_val_loss = val_loss / len(val_loader)

    val_accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    val_precision = precision_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    val_recall = recall_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    val_f1 = f1_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    val_roc_auc = roc_auc_score(
        all_labels,
        all_probabilities
    )

    val_pr_auc = average_precision_score(
        all_labels,
        all_probabilities
    )

    validation_results.append({
        "model": model_idx + 1,
        "val_loss": avg_val_loss,
        "accuracy": val_accuracy,
        "precision": val_precision,
        "recall": val_recall,
        "f1": val_f1,
        "roc_auc": val_roc_auc,
        "pr_auc": val_pr_auc
    })

validation_df = pd.DataFrame(validation_results)

validation_df

,model,val_loss,accuracy,precision,recall,f1,roc_auc,pr_auc
0,1,0.096563,0.964952,0.965403,0.968879,0.967138,0.995091,0.996051
1,2,0.096293,0.964824,0.963509,0.970680,0.967081,0.994994,0.995938
2,3,0.096158,0.964760,0.965753,0.968129,0.966939,0.995101,0.996046
3,4,0.096069,0.965176,0.968385,0.966118,0.967251,0.994998,0.995949
4,5,0.094874,0.964776,0.964863,0.969120,0.966987,0.995116,0.996054

In [23]:
for result in validation_results:
    print(
        f"BERT {result['model']}: "
        f"F1={result['f1']:.4f}, "
        f"Accuracy={result['accuracy']:.4f}, "
        f"ROC-AUC={result['roc_auc']:.4f}, "
        f"PR-AUC={result['pr_auc']:.4f}"
    )

BERT 1: F1=0.9671, Accuracy=0.9650, ROC-AUC=0.9951, PR-AUC=0.9961
BERT 2: F1=0.9671, Accuracy=0.9648, ROC-AUC=0.9950, PR-AUC=0.9959
BERT 3: F1=0.9669, Accuracy=0.9648, ROC-AUC=0.9951, PR-AUC=0.9960
BERT 4: F1=0.9673, Accuracy=0.9652, ROC-AUC=0.9950, PR-AUC=0.9959
BERT 5: F1=0.9670, Accuracy=0.9648, ROC-AUC=0.9951, PR-AUC=0.9961

In [24]:
validation_results = []
validation_predictions = {}

for model_idx, model in enumerate(loaded_models):

    model.eval()

    val_loss = 0.0
    all_labels = []
    all_probabilities = []

    with torch.no_grad():

        for batch in val_loader:

            input_ids = batch["tokenized"].to(device)
            attention_mask = batch["attention_masks"].to(device)
            labels = batch["label"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            val_loss += outputs.loss.item()

            logits = outputs.logits
            probabilities = torch.softmax(logits, dim=1)[:, 1]

            all_labels.extend(labels.cpu().numpy())
            all_probabilities.extend(probabilities.cpu().numpy())

    all_labels = np.array(all_labels)
    all_probabilities = np.array(all_probabilities)

    # Default 0.5 threshold
    all_predictions = (all_probabilities >= 0.5).astype(int)

    avg_val_loss = val_loss / len(val_loader)

    validation_predictions[model_idx + 1] = {
        "labels": all_labels,
        "probabilities": all_probabilities
    }

    validation_results.append({
        "model": model_idx + 1,
        "val_loss": avg_val_loss,
        "accuracy": accuracy_score(all_labels, all_predictions),
        "precision": precision_score(
            all_labels, all_predictions, zero_division=0
        ),
        "recall": recall_score(
            all_labels, all_predictions, zero_division=0
        ),
        "f1": f1_score(
            all_labels, all_predictions, zero_division=0
        ),
        "roc_auc": roc_auc_score(
            all_labels, all_probabilities
        ),
        "pr_auc": average_precision_score(
            all_labels, all_probabilities
        )
    })

validation_df = pd.DataFrame(validation_results)

validation_df

,model,val_loss,accuracy,precision,recall,f1,roc_auc,pr_auc
0,1,0.096563,0.964952,0.965403,0.968879,0.967138,0.995091,0.996051
1,2,0.096293,0.964824,0.963509,0.970680,0.967081,0.994994,0.995938
2,3,0.096158,0.964760,0.965753,0.968129,0.966939,0.995101,0.996046
3,4,0.096069,0.965176,0.968385,0.966118,0.967251,0.994998,0.995949
4,5,0.094874,0.964776,0.964863,0.969120,0.966987,0.995116,0.996054

In [25]:
thresholds = np.arange(0.05, 0.51, 0.05)

threshold_results = []

for model_idx in range(1, len(loaded_models) + 1):

    labels = validation_predictions[model_idx]["labels"]
    probabilities = validation_predictions[model_idx]["probabilities"]

    for threshold in thresholds:

        predictions = (probabilities >= threshold).astype(int)

        threshold_results.append({
            "model": model_idx,
            "threshold": threshold,
            "precision": precision_score(
                labels, predictions, zero_division=0
            ),
            "recall": recall_score(
                labels, predictions, zero_division=0
            ),
            "f1": f1_score(
                labels, predictions, zero_division=0
            ),
            "accuracy": accuracy_score(
                labels, predictions
            )
        })

threshold_df = pd.DataFrame(threshold_results)

threshold_df

    model  threshold  precision    recall        f1  accuracy
0       1       0.05   0.907256  0.991387  0.947457  0.941470
1       1       0.10   0.928022  0.987816  0.956986  0.952732
2       1       0.15   0.938896  0.984965  0.961379  0.957875
3       1       0.20   0.944616  0.982234  0.963058  0.959888
4       1       0.25   0.949429  0.979773  0.964362  0.961454
5       1       0.30   0.953036  0.977432  0.965080  0.962348
6       1       0.35   0.956207  0.975692  0.965851  0.963275
7       1       0.40   0.959027  0.973561  0.966239  0.963786
8       1       0.45   0.962889  0.970980  0.966918  0.964633
9       1       0.50   0.965403  0.968879  0.967138  0.964952
10      2       0.05   0.906136  0.991387  0.946846  0.940751
11      2       0.10   0.925429  0.988056  0.955718  0.951262
12      2       0.15   0.935762  0.985355  0.959918  0.956198
13      2       0.20   0.942236  0.982954  0.962164  0.958850
14      2       0.25   0.946984  0.980974  0.963679  0.960639
15      2       0.30   0.950915  0.979053  0.964779  0.961949
16      2       0.35   0.955503  0.976952  0.966109  0.963514
17      2       0.40   0.958026  0.974701  0.966292  0.963802
18      2       0.45   0.961240  0.972721  0.966946  0.964601
19      2       0.50   0.963509  0.970680  0.967081  0.964824
20      3       0.05   0.917849  0.990457  0.952771  0.947732
21      3       0.10   0.934199  0.987186  0.959961  0.956166
22      3       0.15   0.942366  0.984335  0.962893  0.959617
23      3       0.20   0.947905  0.981814  0.964562  0.961597
24      3       0.25   0.952310  0.979203  0.965569  0.962827
25      3       0.30   0.955107  0.976862  0.965862  0.963243
26      3       0.35   0.957628  0.974641  0.966060  0.963546
27      3       0.40   0.961718  0.972541  0.967099  0.964776
28      3       0.45   0.963949  0.970140  0.967035  0.964792
29      3       0.50   0.965753  0.968129  0.966939  0.964760
30      4       0.05   0.912797  0.989827  0.949752  0.944249
31      4       0.10   0.933295  0.985055  0.958477  0.954569
32      4       0.15   0.942745  0.982354  0.962142  0.958850
33      4       0.20   0.948609  0.979383  0.963750  0.960783
34      4       0.25   0.952986  0.976952  0.964820  0.962077
35      4       0.30   0.957214  0.974851  0.965952  0.963419
36      4       0.35   0.960785  0.972751  0.966731  0.964361
37      4       0.40   0.963021  0.970680  0.966836  0.964553
38      4       0.45   0.965190  0.968579  0.966882  0.964681
39      4       0.50   0.968385  0.966118  0.967251  0.965176
40      5       0.05   0.908598  0.991327  0.948162  0.942300
41      5       0.10   0.929023  0.988296  0.957743  0.953578
42      5       0.15   0.938288  0.985115  0.961131  0.957588
43      5       0.20   0.945054  0.982774  0.963545  0.960415
44      5       0.25   0.950087  0.980253  0.964935  0.962077
45      5       0.30   0.954024  0.978303  0.966011  0.963355
46      5       0.35   0.957724  0.975602  0.966580  0.964089
47      5       0.40   0.960356  0.973441  0.966854  0.964473
48      5       0.45   0.962472  0.971310  0.966871  0.964569
49      5       0.50   0.964863  0.969120  0.966987  0.964776

In [8]:
import time
import numpy as np
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

all_model_probabilities = []
test_labels = None

ensemble_start = time.perf_counter()

for model_idx, model in enumerate(loaded_models):

    print(f"\nStarting model {model_idx + 1}/{len(loaded_models)}", flush=True)

    model.eval()

    model_probabilities = []
    model_labels = []

    model_start = time.perf_counter()

    with torch.no_grad():

        for batch_idx, batch in enumerate(test_loader):

            # Print progress every 10 batches
            if batch_idx % 10 == 0:
                print(
                    f"  Model {model_idx + 1}: "
                    f"processing batch {batch_idx}",
                    flush=True
                )

            input_ids = batch["tokenized"].to(device)
            attention_mask = batch["attention_masks"].to(device)
            labels = batch["label"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            probabilities = torch.softmax(
                outputs.logits,
                dim=1
            )[:, 1]

            model_probabilities.extend(
                probabilities.detach().cpu().numpy()
            )

            model_labels.extend(
                labels.detach().cpu().numpy()
            )

    # Synchronize only AFTER this model is finished
    if device.type == "cuda":
        torch.cuda.synchronize()

    model_time = time.perf_counter() - model_start

    all_model_probabilities.append(
        np.array(model_probabilities)
    )

    if test_labels is None:
        test_labels = np.array(model_labels)

    print(
        f"Finished model {model_idx + 1}: "
        f"{len(model_probabilities)} predictions | "
        f"{model_time:.2f} seconds",
        flush=True
    )


if device.type == "cuda":
    torch.cuda.synchronize()

total_inference_time = time.perf_counter() - ensemble_start

print("\n====================================")
print(f"Total inference time: {total_inference_time:.2f} seconds")
print(f"Number of examples: {len(test_labels)}")

latency_per_example = (
    total_inference_time / len(test_labels)
)

print(
    f"Ensemble latency per example: "
    f"{latency_per_example * 1000:.3f} ms"
)

print("====================================")

Starting model 1/5
  Model 1: processing batch 0
  Model 1: processing batch 10
  Model 1: processing batch 20
  Model 1: processing batch 30
  Model 1: processing batch 40
  Model 1: processing batch 50
  Model 1: processing batch 60
  Model 1: processing batch 70
  Model 1: processing batch 80
  Model 1: processing batch 90
  Model 1: processing batch 100
  Model 1: processing batch 110
  Model 1: processing batch 120
  Model 1: processing batch 130
  Model 1: processing batch 140
  Model 1: processing batch 150
  Model 1: processing batch 160
  Model 1: processing batch 170
  Model 1: processing batch 180
  Model 1: processing batch 190
  Model 1: processing batch 200
  Model 1: processing batch 210
  Model 1: processing batch 220
  Model 1: processing batch 230
  Model 1: processing batch 240
  Model 1: processing batch 250
  Model 1: processing batch 260
  Model 1: processing batch 270
  Model 1: processing batch 280
  Model 1: processing batch 290
  Model 1: processing batch 300
  Model 1: processing batch 310
  Model 1: processing batch 320
  Model 1: processing batch 330
  Model 1: processing batch 340
  Model 1: processing batch 350
  Model 1: processing batch 360
  Model 1: processing batch 370
  Model 1: processing batch 380
  Model 1: processing batch 390
  Model 1: processing batch 400
  Model 1: processing batch 410
  Model 1: processing batch 420
  Model 1: processing batch 430
  Model 1: processing batch 440
  Model 1: processing batch 450
  Model 1: processing batch 460
  Model 1: processing batch 470
  Model 1: processing batch 480
  Model 1: processing batch 490
  Model 1: processing batch 500
  Model 1: processing batch 510
  Model 1: processing batch 520
  Model 1: processing batch 530
  Model 1: processing batch 540
  Model 1: processing batch 550
  Model 1: processing batch 560
  Model 1: processing batch 570
  Model 1: processing batch 580
  Model 1: processing batch 590
  Model 1: processing batch 600
  Model 1: processing batch 610
  Model 1: processing batch 620
  Model 1: processing batch 630
Finished model 1: 63139 predictions | 316.35 seconds

Starting model 2/5
  Model 2: processing batch 0
  Model 2: processing batch 10
  Model 2: processing batch 20
  Model 2: processing batch 30
  Model 2: processing batch 40
  Model 2: processing batch 50
  Model 2: processing batch 60
  Model 2: processing batch 70
  Model 2: processing batch 80
  Model 2: processing batch 90
  Model 2: processing batch 100
  Model 2: processing batch 110
  Model 2: processing batch 120
  Model 2: processing batch 130
  Model 2: processing batch 140
  Model 2: processing batch 150
  Model 2: processing batch 160
  Model 2: processing batch 170
  Model 2: processing batch 180
  Model 2: processing batch 190
  Model 2: processing batch 200
  Model 2: processing batch 210
  Model 2: processing batch 220
  Model 2: processing batch 230
  Model 2: processing batch 240
  Model 2: processing batch 250
  Model 2: processing batch 260
  Model 2: processing batch 270
  Model 2: processing batch 280
  Model 2: processing batch 290
  Model 2: processing batch 300
  Model 2: processing batch 310
  Model 2: processing batch 320
  Model 2: processing batch 330
  Model 2: processing batch 340
  Model 2: processing batch 350
  Model 2: processing batch 360
  Model 2: processing batch 370
  Model 2: processing batch 380
  Model 2: processing batch 390
  Model 2: processing batch 400
  Model 2: processing batch 410
  Model 2: processing batch 420
  Model 2: processing batch 430
  Model 2: processing batch 440
  Model 2: processing batch 450
  Model 2: processing batch 460
  Model 2: processing batch 470
  Model 2: processing batch 480
  Model 2: processing batch 490
  Model 2: processing batch 500
  Model 2: processing batch 510
  Model 2: processing batch 520
  Model 2: processing batch 530
  Model 2: processing batch 540
  Model 2: processing batch 550
  Model 2: processing batch 560
  Model 2: processing batch 570
  Model 2: processing batch 580
  Model 2: processing batch 590
  Model 2: processing batch 600
  Model 2: processing batch 610
  Model 2: processing batch 620
  Model 2: processing batch 630
Finished model 2: 63139 predictions | 272.74 seconds

Starting model 3/5
  Model 3: processing batch 0
  Model 3: processing batch 10
  Model 3: processing batch 20
  Model 3: processing batch 30
  Model 3: processing batch 40
  Model 3: processing batch 50
  Model 3: processing batch 60
  Model 3: processing batch 70
  Model 3: processing batch 80
  Model 3: processing batch 90
  Model 3: processing batch 100
  Model 3: processing batch 110
  Model 3: processing batch 120
  Model 3: processing batch 130
  Model 3: processing batch 140
  Model 3: processing batch 150
  Model 3: processing batch 160
  Model 3: processing batch 170
  Model 3: processing batch 180
  Model 3: processing batch 190
  Model 3: processing batch 200
  Model 3: processing batch 210
  Model 3: processing batch 220
  Model 3: processing batch 230
  Model 3: processing batch 240
  Model 3: processing batch 250
  Model 3: processing batch 260
  Model 3: processing batch 270
  Model 3: processing batch 280
  Model 3: processing batch 290
  Model 3: processing batch 300
  Model 3: processing batch 310
  Model 3: processing batch 320
  Model 3: processing batch 330
  Model 3: processing batch 340
  Model 3: processing batch 350
  Model 3: processing batch 360
  Model 3: processing batch 370
  Model 3: processing batch 380
  Model 3: processing batch 390
  Model 3: processing batch 400
  Model 3: processing batch 410
  Model 3: processing batch 420
  Model 3: processing batch 430
  Model 3: processing batch 440
  Model 3: processing batch 450
  Model 3: processing batch 460
  Model 3: processing batch 470
  Model 3: processing batch 480
  Model 3: processing batch 490
  Model 3: processing batch 500
  Model 3: processing batch 510
  Model 3: processing batch 520
  Model 3: processing batch 530
  Model 3: processing batch 540
  Model 3: processing batch 550
  Model 3: processing batch 560
  Model 3: processing batch 570
  Model 3: processing batch 580
  Model 3: processing batch 590
  Model 3: processing batch 600
  Model 3: processing batch 610
  Model 3: processing batch 620
  Model 3: processing batch 630
Finished model 3: 63139 predictions | 267.30 seconds

Starting model 4/5
  Model 4: processing batch 0
  Model 4: processing batch 10
  Model 4: processing batch 20
  Model 4: processing batch 30
  Model 4: processing batch 40
  Model 4: processing batch 50
  Model 4: processing batch 60
  Model 4: processing batch 70
  Model 4: processing batch 80
  Model 4: processing batch 90
  Model 4: processing batch 100
  Model 4: processing batch 110
  Model 4: processing batch 120
  Model 4: processing batch 130
  Model 4: processing batch 140
  Model 4: processing batch 150
  Model 4: processing batch 160
  Model 4: processing batch 170
  Model 4: processing batch 180
  Model 4: processing batch 190
  Model 4: processing batch 200
  Model 4: processing batch 210
  Model 4: processing batch 220
  Model 4: processing batch 230
  Model 4: processing batch 240
  Model 4: processing batch 250
  Model 4: processing batch 260
  Model 4: processing batch 270
  Model 4: processing batch 280
  Model 4: processing batch 290
  Model 4: processing batch 300
  Model 4: processing batch 310
  Model 4: processing batch 320
  Model 4: processing batch 330
  Model 4: processing batch 340
  Model 4: processing batch 350
  Model 4: processing batch 360
  Model 4: processing batch 370
  Model 4: processing batch 380
  Model 4: processing batch 390
  Model 4: processing batch 400
  Model 4: processing batch 410
  Model 4: processing batch 420
  Model 4: processing batch 430
  Model 4: processing batch 440
  Model 4: processing batch 450
  Model 4: processing batch 460
  Model 4: processing batch 470
  Model 4: processing batch 480
  Model 4: processing batch 490
  Model 4: processing batch 500
  Model 4: processing batch 510
  Model 4: processing batch 520
  Model 4: processing batch 530
  Model 4: processing batch 540
  Model 4: processing batch 550
  Model 4: processing batch 560
  Model 4: processing batch 570
  Model 4: processing batch 580
  Model 4: processing batch 590
  Model 4: processing batch 600
  Model 4: processing batch 610
  Model 4: processing batch 620
  Model 4: processing batch 630
Finished model 4: 63139 predictions | 280.24 seconds

Starting model 5/5
  Model 5: processing batch 0
  Model 5: processing batch 10
  Model 5: processing batch 20
  Model 5: processing batch 30
  Model 5: processing batch 40
  Model 5: processing batch 50
  Model 5: processing batch 60
  Model 5: processing batch 70
  Model 5: processing batch 80
  Model 5: processing batch 90
  Model 5: processing batch 100
  Model 5: processing batch 110
  Model 5: processing batch 120
  Model 5: processing batch 130
  Model 5: processing batch 140
  Model 5: processing batch 150
  Model 5: processing batch 160
  Model 5: processing batch 170
  Model 5: processing batch 180
  Model 5: processing batch 190
  Model 5: processing batch 200
  Model 5: processing batch 210
  Model 5: processing batch 220
  Model 5: processing batch 230
  Model 5: processing batch 240
  Model 5: processing batch 250
  Model 5: processing batch 260
  Model 5: processing batch 270
  Model 5: processing batch 280
  Model 5: processing batch 290
  Model 5: processing batch 300
  Model 5: processing batch 310
  Model 5: processing batch 320
  Model 5: processing batch 330
  Model 5: processing batch 340
  Model 5: processing batch 350
  Model 5: processing batch 360
  Model 5: processing batch 370
  Model 5: processing batch 380
  Model 5: processing batch 390
  Model 5: processing batch 400
  Model 5: processing batch 410
  Model 5: processing batch 420
  Model 5: processing batch 430
  Model 5: processing batch 440
  Model 5: processing batch 450
  Model 5: processing batch 460
  Model 5: processing batch 470
  Model 5: processing batch 480
  Model 5: processing batch 490
  Model 5: processing batch 500
  Model 5: processing batch 510
  Model 5: processing batch 520
  Model 5: processing batch 530
  Model 5: processing batch 540
  Model 5: processing batch 550
  Model 5: processing batch 560
  Model 5: processing batch 570
  Model 5: processing batch 580
  Model 5: processing batch 590
  Model 5: processing batch 600
  Model 5: processing batch 610
  Model 5: processing batch 620
  Model 5: processing batch 630
Finished model 5: 63139 predictions | 264.35 seconds

====================================
Total inference time: 1401.13 seconds
Number of examples: 63139
Ensemble latency per example: 22.191 ms
====================================

In [9]:
num_test_examples = len(test_labels)

latency_per_example = (
    total_inference_time / num_test_examples
)

print(f"Number of test examples: {num_test_examples}")
print(f"Latency per example: {latency_per_example:.6f} seconds")
print(
    f"Latency per example: "
    f"{latency_per_example * 1000:.3f} ms"
)

Number of test examples: 63139
Latency per example: 0.022191 seconds
Latency per example: 22.191 ms